### PR TITLE
Add PPLNS SOLO WoolyPooly

### PR DESCRIPTION
**Pull request by PcDeaDZ**
Add PPLNS SOLO WoolyPooly

### CODE REVIEW

**Comment by KforG** [comment]
I think we should withhold from including solo pools in OCM. Especially since they will be picked randomly for new users.

**Comment by riksarchen** [comment]
Id 9 is taken by Miningpoolsweden

**Comment by PcDeaDZ** [comment]
> Id 9 is taken by Miningpoolsweden

11 now

**Comment by riksarchen** [comment]
You need to update pool.go aswell

**Review by mahamadmansor — COMMENTED** [review]
Good

**Comment by mahamadmansor** [comment]
Oki

**Comment by gertjaap** [comment]
Doesn't compile this way. The files should get a `.go` extension.

Also with @KforG on not adding solo pools. So without the solo one, and proper extension it could go in. Not like this.

**Pull request closed without merging**
